# -*- coding: utf-8 -*-
"""menu.txt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Eiq-QB6lwe4fKBCVzFe9YO10Cqs5Da4
"""

print("""

 Lütfen Bir Pizza Tabanı Seçiniz:
1: Klasik pizza
2: Margarita pizza
3: TürkPizza
4: Sade Pizza


----------------
Seçeceğiniz sos:
5:Zeytin
6: Mantarlar
7: Keçi Peyniri
8: Et
9: Soğan
10: Mısır
11: Kıyma
12: Sucuk

    
""")