# -*- coding: utf-8 -*-
"""Orders_Database.csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r39O5KOqKqTswLwPhrNpjIpi3ItcJ3wR
"""

#@title Orders_Database.csv
İsim:T.C. no;                kredi kartı numarası   zaman  şifre                    
Hatice:51794501268;          8888-2222-3333-4444;;;-;09.37;2055
Samet:18457802962;           6666-5555-7777-1111;;;-;21.21;5555
Talat:48231501585;           0000-0000-3333-9999;;;-;14.21;3547